[package]
edition = "2018"
name = "builder-swc"
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0"
backtrace = "0.3"
chrono = "0.4"
easy-error = "1.0.0"
napi = { version = "1", features = ["serde-json"] }
napi-derive = "1"
path-clean = "0.1"
regex = "1.5"
serde = "1"
serde_json = "1"
swc = "0.95.0"
swc_atoms = "0.2.7"
swc_common = { version = "0.15.0", features = ["concurrent", "sourcemap"] }
swc_css = "0.44.0"
swc_ecma_loader = { version = "0.25.0", features = ["node", "lru"] }
swc_ecmascript = { version = "0.95.0", features = ["codegen", "minifier", "optimization", "parser", "react", "transforms", "typescript", "utils", "visit"] }
swc_node_base = "0.5.1"
swc_stylis = "0.41.0"
fxhash = "0.2.1"
retain_mut = "0.1.3"
pathdiff = "0.2.0"
rustc-hash = "1.1.0"
tracing = { version = "0.1.28", features = ["release_max_level_off"] }
lazy_static = "1.4.0"

[dev-dependencies]
swc_ecma_transforms_testing = "0.49.0"
testing = "0.16.0"
walkdir = "2.3.2"

[build-dependencies]
napi-build = "1"

[profile.release]
lto = true
