name: CI

on: [push]

jobs:
  # Build binaries for publishing
  build-native:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - host: macos-latest
            target: 'x86_64-apple-darwin'
          - host: windows-latest
            target: 'x86_64-pc-windows-msvc'
          - host: windows-latest
            target: 'i686-pc-windows-msvc'
          - host: ubuntu-latest
            target: 'x86_64-unknown-linux-gnu'
          - host: ubuntu-latest
            target: 'x86_64-unknown-linux-musl'
          - host: macos-latest
            target: 'aarch64-apple-darwin'
          - host: ubuntu-latest
            target: 'aarch64-unknown-linux-gnu'
          - host: ubuntu-latest
            target: 'aarch64-unknown-linux-musl'
          - host: windows-latest
            target: 'aarch64-pc-windows-msvc'
    name: stable - ${{ matrix.settings.target }} - node@12
    runs-on: ${{ matrix.settings.host }}
    steps:
      - uses: actions/checkout@v2
      - name: Set branch name
        run: echo >>$GITHUB_ENV BRANCH_NAME=${GITHUB_REF#refs/heads/}
      - name: Echo branch name
        run: echo ${BRANCH_NAME}
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - run: npm run setup
      - run: npm run ci
